var productsData = {
    data : [
        {
            id: 'p1',
            name: 'Running Unisex Shoes',
            url:'common/shoes_images/shoe1.png',
            price : 1400,
            isSelected : false,
            category: 'Shoes',
            gender: 'Both',
            brand : 'Puma',
            size : 7,
            num_reviews: 200,
            rating : 4.5,
        },
        {
            id: 'p2',
            name: 'Running Men Shoes',
            url:'common/shoes_images/shoe2.png',
            price : 2000,
            isSelected : false,
            category: 'Shoes',
            gender: 'Male',
            brand : 'Nike',
            size : 8,
            num_reviews: 100,
            rating : 3.5,
        },
        {
            id: 'p3',
            name: 'Air Jordan 1 Mid',
            url:'common/shoes_images/shoe3.png',
            price : 10295,
            isSelected : false,
            category: 'Shoes',
            gender: 'Male',
            brand : 'Nike',
            size : 9,
            num_reviews: 455,
            rating : 4,
        },
        {
            id: 'p4',
            name: 'Nike Air Max 90',
            url:'common/shoes_images/shoe4.png',
            price : 10795,
            isSelected : false,
            category: 'Shoes',
            gender: 'Male',
            brand : 'Nike',
            size : 6,
            num_reviews: 450,
            rating : 4.5,
        },
        {
            id: 'p5',
            name: 'Nike Air Pegasus 83 Premium',
            url:'common/shoes_images/shoe5.png',
            price : 8495,
            isSelected : false,
            category: 'Shoes',
            gender: 'Male',
            brand : 'Nike',
            size : 7,
            num_reviews: 70,
            rating : 4,
        },
        {
            id: 'p6',
            name: 'Solid Wood Coffee Table',
            url:'common/tableImages/table1.png',
            price : 13999,
            isSelected : false,
            category: 'Table',
            num_reviews: 70,
            rating : 4,
        },
        {
            id: 'p7',
            name: 'Solid Wood Study Table',
            url:'common/tableImages/table2.png',
            price : 16713,
            isSelected : false,
            category: 'Table',
            num_reviews: 80,
            rating : 4.5,
        },
    ],
};

export default productsData;